"use client";
import {
  Box,
  Typography,
  Card,
  CardContent,
  Avatar,
  Autocomplete,
  TextField,
  InputAdornment,
} from "@mui/material";
import {
  Search,
  Lock,
  KeyRound,
  Users,
  CreditCard,
  UserCircle,
  TrendingUp,
  Database,
  PenTool,
  Plug,
  BookOpen,
  Origami,
  Layers,
  Settings as SettingsIcon,
  ListTodo,
  TriangleAlert,
  CheckCircle,
  GitBranch,
  BarChart3,
  MessageSquare,
  Globe,
  FileText,
  Mail,
  FileBarChart,
  Star,
  MapPin,
  Palette,
  FormInput,
  LockKeyhole,
  FileInput,
  Blocks,
  Puzzle,
  ToggleLeft,
  Home,
  Filter,
} from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";

interface SettingCard {
  icon: React.ReactNode;
  title: string;
  description: string;
  id: string;
}

const userManagementCards: SettingCard[] = [
  {
    id: "authentication",
    icon: <Lock size={20} />,
    title: "Authentication",
    description: "Set the authentication method and LDAP settings",
  },
  {
    id: "oauth_client_applications",
    icon: <Lock size={20} />,
    title: "OAuth Client Applications",
    description:
      "OAuth client configuration for user-initiated integrations (MCP, pipelines)",
  },
  {
    id: "encryption_key_rotation",
    icon: <KeyRound size={20} />,
    title: "Encryption Key Rotation",
    description: "Rotate encryption keys for credentials and user data",
  },
  {
    id: "groups",
    icon: <Users size={20} />,
    title: "Groups",
    description: "Manage groups defined in Alation and by LDAP",
  },
  {
    id: "licenses",
    icon: <CreditCard size={20} />,
    title: "Licenses",
    description: "License consumption dashboard",
  },
  {
    id: "users",
    icon: <UserCircle size={20} />,
    title: "Users",
    description: "Manage your users and their permissions",
  },
  {
    id: "user_profiles",
    icon: <UserCircle size={20} />,
    title: "User Profiles",
    description: "Upload user profiles in bulk",
  },
];

const platformSettingsCards: SettingCard[] = [
  {
    id: "alation_analytics_settings",
    icon: <TrendingUp size={20} />,
    title: "Alation Analytics Settings",
    description: "Configure Settings for AAv2",
  },
  {
    id: "agents",
    icon: <Database size={20} />,
    title: "Agents",
    description: "Manage Alation Agents",
  },
  {
    id: "compose_settings",
    icon: <PenTool size={20} />,
    title: "Compose Settings",
    description: "Set 'My Queries' on Homepage and other settings",
  },
  {
    id: "connectors",
    icon: <Plug size={20} />,
    title: "Connectors",
    description: "Manage Connectors",
  },
  {
    id: "lexicon_settings",
    icon: <BookOpen size={20} />,
    title: "Lexicon Settings",
    description: "Manage titles generated by Alation",
  },
  {
    id: "lineage_settings",
    icon: <Layers size={20} />,
    title: "Lineage Settings",
    description: "Manage Lineage related settings",
  },
  {
    id: "data_quality_settings",
    icon: <Layers size={20} />,
    title: "Data Quality Settings",
    description: "Configure data quality rules and monitoring",
  },
];

const systemMonitorCards: SettingCard[] = [
  {
    id: "active_tasks",
    icon: <ListTodo size={20} />,
    title: "Active Tasks",
    description: "Monitor currently running tasks",
  },
  {
    id: "alerts",
    icon: <TriangleAlert size={20} />,
    title: "Alerts",
    description: "Configure system alerts and notifications",
  },
  {
    id: "completed_tasks",
    icon: <CheckCircle size={20} />,
    title: "Completed Tasks",
    description: "View history of completed tasks",
  },
  {
    id: "etl_status",
    icon: <GitBranch size={20} />,
    title: "ETL Status",
    description: "Monitor ETL job status and performance",
  },
  {
    id: "logging",
    icon: <BarChart3 size={20} />,
    title: "Logging",
    description: "View and configure system logs",
  },
  {
    id: "message_queues",
    icon: <MessageSquare size={20} />,
    title: "Message Queues",
    description: "Monitor message queue status",
  },
  {
    id: "online_users",
    icon: <Globe size={20} />,
    title: "Online Users",
    description: "View currently active users",
  },
  {
    id: "scheduled_query_dashboard",
    icon: <FileText size={20} />,
    title: "Scheduled Query Dashboard",
    description: "Monitor scheduled queries",
  },
];

const systemAdministrationCards: SettingCard[] = [
  {
    id: "email_server_settings",
    icon: <Mail size={20} />,
    title: "Email Server Settings",
    description: "Configure email server and notifications",
  },
  {
    id: "reporting",
    icon: <FileBarChart size={20} />,
    title: "Reporting",
    description: "Configure reporting settings",
  },
  {
    id: "miscellaneous",
    icon: <Star size={20} />,
    title: "Miscellaneous",
    description: "Additional system settings",
  },
  {
    id: "ip_access_management",
    icon: <MapPin size={20} />,
    title: "IP Access Management",
    description: "Configure IP whitelisting and access control",
  },
];

const customizationCards: SettingCard[] = [
  {
    id: "custom_templates",
    icon: <Blocks size={20} />,
    title: "Custom Templates",
    description: "Create custom templates for catalog pages",
  },
  {
    id: "custom_fields",
    icon: <FormInput size={20} />,
    title: "Custom Fields & Permissions",
    description: "Create and manage custom fields and their permissions",
  },
  {
    id: "custom_asset_types",
    icon: <Origami size={20} />,
    title: "Custom Asset Types",
    description: "Define custom asset types for your catalog",
  },
  {
    id: "homepage_customization",
    icon: <Home size={20} />,
    title: "Homepage Customization",
    description: "Customize homepage layouts and content",
  },
  {
    id: "search_filter_customization",
    icon: <Filter size={20} />,
    title: "Search Filter Customization",
    description: "Customize search filters and facets",
  },
  {
    id: "branding_options",
    icon: <Palette size={20} />,
    title: "Branding Options",
    description: "Customize the look and feel of your instance",
  },
  {
    id: "feature_configuration",
    icon: <ToggleLeft size={20} />,
    title: "Feature Configuration",
    description: "Enable or disable features",
  },
];

interface SettingSection {
  id: string;
  title: string;
  cards: SettingCard[];
}

const allSections: SettingSection[] = [
  {
    id: "user-management",
    title: "User Management",
    cards: userManagementCards,
  },
  {
    id: "platform-settings",
    title: "Platform Settings",
    cards: platformSettingsCards,
  },
  {
    id: "system-monitor",
    title: "System Monitor",
    cards: systemMonitorCards,
  },
  {
    id: "system-administration",
    title: "System Administration",
    cards: systemAdministrationCards,
  },
  {
    id: "customization",
    title: "Catalog Customization",
    cards: customizationCards,
  },
];

const allCards = allSections.flatMap((section) => section.cards);

function SettingCardComponent({ card }: { card: SettingCard }) {
  const router = useRouter();

  const handleClick = () => {
    router.push(`/app/settings/${card.id}`);
  };

  return (
    <Card
      onClick={handleClick}
      variant="outlined"
      sx={{
        cursor: "pointer",
        bgcolor: "transparent",
        minHeight: "98px",
        display: "flex",
        alignItems: "center",
        transition: "all 0.2s",
        "&:hover": {
          boxShadow: 1,
          borderColor: "grey.500",
        },
      }}
    >
      <CardContent sx={{ p: 0, width: "100%", "&:last-child": { pb: 0 } }}>
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            gap: 2,
            p: 2,
          }}
        >
          <Avatar
            sx={{
              bgcolor: "#ECF6FF",
              width: 40,
              height: 40,
            }}
          >
            <Box sx={{ color: "#0073DD" }}>{card.icon}</Box>
          </Avatar>
          <Box sx={{ flex: 1, minWidth: 0 }}>
            <Typography
              variant="h6"
              sx={{
                fontSize: "16px",
                fontWeight: 600,
                mb: 0.5,
                lineHeight: 1.3,
                color: "text.primary",
              }}
            >
              {card.title}
            </Typography>
            <Typography
              variant="body1"
              sx={{
                color: "text.secondary",
                fontSize: "14px",
                lineHeight: 1.4,
              }}
            >
              {card.description}
            </Typography>
          </Box>
        </Box>
      </CardContent>
    </Card>
  );
}

export default function SettingsPage() {
  const router = useRouter();
  const [selectedCard, setSelectedCard] = useState<SettingCard | null>(null);

  const handleAutocompleteChange = (_: any, newValue: SettingCard | null) => {
    if (newValue) {
      router.push(`/app/settings/${newValue.id}`);
    }
    setSelectedCard(null);
  };

  return (
    <Box sx={{ width: "100%", height: "100%", overflow: "auto" }}>
      <Box sx={{ maxWidth: "1400px", margin: "0 auto", p: 4 }}>
        <Typography
          variant="h1"
          sx={{ mb: 3 }}
        >
          Admin Settings
        </Typography>

        <Autocomplete
          options={allCards}
          getOptionLabel={(option) => option.title}
          value={selectedCard}
          onChange={handleAutocompleteChange}
          renderInput={({ InputProps, ...params }) => (
            <TextField
              {...params}
              placeholder="Search for a section"
              size="small"
              variant="outlined"
              slotProps={{
                input: {
                  ...(InputProps as any),
                  startAdornment: (
                    <>
                      <InputAdornment position="start">
                        <Search size={20} />
                      </InputAdornment>
                      {InputProps.startAdornment}
                    </>
                  ),
                },
              }}
            />
          )}
          renderOption={(props, option) => {
            const { key, ...otherProps } = props as any;
            return (
              <Box component="li" key={key} {...otherProps} sx={{ p: 0 }}>
                <Box sx={{ width: "100%", p: 1 }}>
                  <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
                    <Avatar
                      sx={{
                        bgcolor: "#ECF6FF",
                        width: 32,
                        height: 32,
                      }}
                    >
                      <Box sx={{ color: "#0073DD" }}>{option.icon}</Box>
                    </Avatar>
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                      <Typography
                        sx={{
                          fontSize: "14px",
                          fontWeight: 600,
                          lineHeight: 1.2,
                          color: "text.primary",
                        }}
                      >
                        {option.title}
                      </Typography>
                      <Typography
                        variant="body1"
                        sx={{
                          color: "text.secondary",
                          fontSize: "12px",
                          lineHeight: 1.3,
                        }}
                      >
                        {option.description}
                      </Typography>
                    </Box>
                  </Box>
                </Box>
              </Box>
            );
          }}
          sx={{
            mb: 4,
            "& .MuiOutlinedInput-root": {
              backgroundColor: "white",
            },
          }}
        />

        {allSections.map((section) => (
          <Box key={section.id} sx={{ mb: 5 }}>
            <Typography
              variant="h5"
              sx={{ mb: 3, fontWeight: 600, fontSize: "20px" }}
            >
              {section.title}
            </Typography>
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))",
                gap: 2,
              }}
            >
              {section.cards.map((card) => (
                <SettingCardComponent key={card.id} card={card} />
              ))}
            </Box>
          </Box>
        ))}
      </Box>
    </Box>
  );
}
