import { colorPalette } from "./palette";

export const semanticColorTokens = {
  color: {
    border: {
      default: colorPalette.neutral[300],
      hover: colorPalette.neutral[400],
      disabled: colorPalette.neutral[200],
      focused: colorPalette.blue[600],
      error: colorPalette.red[600],
      warning: colorPalette.amber[600],
      information: colorPalette.blue[600],
      success: colorPalette.green[600],
      table: "rgb(240, 240, 240)",
      button: {
        primary: colorPalette.blue[600],
        focus: colorPalette.blue[900],
        error: colorPalette.red[600],
      },
      selected: colorPalette.neutral[500],
      misc: {
        placeholder: colorPalette.pink[500],
      },
    },
    background: {
      control: {
        default: "#ffffff",
        warning: colorPalette.amber[200],
        error: colorPalette.red[200],
        information: colorPalette.blue[200],
        success: colorPalette.green[200],
        disabled: colorPalette.neutral[50],
        hover: colorPalette.neutral[100],
        secondary: colorPalette.neutral[100],
        "secondary-hover": colorPalette.neutral[200],
        selected: colorPalette.neutral[100],
        inverted: colorPalette.neutral[800],
      },
      accent: {
        gray: colorPalette.neutral[200],
        blue: colorPalette.blue[200],
        red: colorPalette.red[200],
        amber: colorPalette.amber[200],
        green: colorPalette.green[200],
        teal: colorPalette.teal[200],
        purple: colorPalette.purple[200],
        pink: colorPalette.pink[200],
        orange: colorPalette.orange[200],
      },
      surface: {
        secondary: colorPalette.neutral[50],
        default: "#ffffff",
        modal: {
          // gray[800] with 70% opacity: rgba(39, 39, 42, 0.700)
          backdrop: "rgba(39, 39, 42, 0.700)",
        },
      },
      scrollbar: {
        default: colorPalette.neutral[300],
        hover: colorPalette.neutral[400],
      },
      chip: {
        gray: colorPalette.neutral[200],
        blue: colorPalette.blue[200],
        red: colorPalette.red[200],
        amber: colorPalette.amber[200],
        green: colorPalette.green[200],
        teal: colorPalette.teal[200],
        purple: colorPalette.purple[200],
        pink: colorPalette.pink[200],
        "gray-strong": colorPalette.neutral[600],
        "blue-strong": colorPalette.blue[600],
        "red-strong": colorPalette.red[600],
        "amber-strong": colorPalette.amber[600],
        "green-strong": colorPalette.green[600],
        "teal-strong": colorPalette.teal[600],
        "purple-strong": colorPalette.purple[600],
        "pink-strong": colorPalette.pink[600],
        orange: colorPalette.orange[200],
        "orange-strong": colorPalette.orange[600],
      },
      button: {
        primary: colorPalette.blue[600],
        "primary-hover": colorPalette.blue[700],
        "secondary-hover": colorPalette.blue[100],
        error: colorPalette.red[600],
        "error-hover": colorPalette.red[700],
        "error-secondary-hover": colorPalette.red[100],
      },
      avatar: {
        default: colorPalette.blue[600],
        subtle: colorPalette.neutral[300],
      },
      progress: {
        primary: colorPalette.blue[600],
      },
      misc: {
        placeholder: colorPalette.pink[100],
      },
    },
    text: {
      primary: colorPalette.neutral[900],
      secondary: colorPalette.neutral[600],
      disabled: colorPalette.neutral[400],
      warning: colorPalette.amber[600],
      error: colorPalette.red[600],
      information: colorPalette.blue[600],
      success: colorPalette.green[600],
      chip: {
        gray: colorPalette.neutral[600],
        blue: colorPalette.blue[600],
        red: colorPalette.red[600],
        amber: colorPalette.amber[600],
        green: colorPalette.green[600],
        teal: colorPalette.teal[600],
        purple: colorPalette.purple[600],
        pink: colorPalette.pink[600],
        orange: colorPalette.orange[600],
      },
      inverted: colorPalette.neutral[50],
      button: {
        primary: colorPalette.blue[600],
      },
      "error-disabled": colorPalette.red[400],
    },
    icon: {
      primary: colorPalette.neutral[900],
      secondary: colorPalette.neutral[600],
      information: colorPalette.blue[600],
      success: colorPalette.green[600],
      error: colorPalette.red[600],
      warning: colorPalette.amber[600],
      inverted: colorPalette.neutral[50],
      button: {
        primary: colorPalette.blue[600],
      },
      disabled: colorPalette.neutral[400],
      "error-disabled": colorPalette.red[400],
    },
    white: "#ffffff",
    transparent: "transparent",
    "transparent-001": "rgba(255, 255, 255, 0.010)",
  },
} as const;
